service: doodle-hours

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: ">=1.28.0 <2.0.0"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2
  memorySize: 128
  timeout: 30
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${self:custom.nodeEnv.${opt:stage, self:provider.stage}, 'development'}
    AIRTABLE_API_KEY: ${env:AIRTABLE_API_KEY}
    AIRTABLE_BASE_ID: ${env:AIRTABLE_BASE_ID}

functions:
  app:
    handler: ./functions/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

custom:
  nodeEnv:
    dev: "development"
    prod: "production"
  serverless-offline:
    port: 9000